listen-address=192.168.1.191
bind-interfaces
port=53
no-resolv
no-hosts
server=1.1.1.1
server=8.8.8.8
filter-AAAA
address=/rt.waze.com/192.168.1.191
address=/www.waze.com/192.168.1.191
address=/row.waze.com/192.168.1.191
address=/config.waze.com/192.168.1.191
address=/desc.waze.com/192.168.1.191
address=/rtserver.waze.com/192.168.1.191
address=/rt-old-client/192.168.1.191
address=/waze.com/192.168.1.191
address=/waze-client-resources.s3.amazonaws.com/192.168.1.191
address=/rtproxy-na.waze.com/192.168.1.191
address=/rtproxy-row.waze.com/192.168.1.191
address=/ctiles-na.waze.com/192.168.1.191
address=/ctiles-g-am.waze.com/192.168.1.191
address=/tiles.waze.com/192.168.1.191
address=/tiles1.waze.com/192.168.1.191
address=/tiles2.waze.com/192.168.1.191
address=/tiles3.waze.com/192.168.1.191
address=/tiles4.waze.com/192.168.1.191
address=/tilesworld1.waze.com/192.168.1.191
address=/livemap-tiles1.waze.com/192.168.1.191
address=/etiles1.waze.com/192.168.1.191
address=/rt.world.waze.com/192.168.1.191
address=/rt-il.waze.com/192.168.1.191
address=/search.waze.com/192.168.1.191
address=/search-lb.waze.com/192.168.1.191
address=/gapi.waze.com/192.168.1.191
log-queries
log-facility=/home/tordjman/Documents/Projets/waze-ios6/logs/dnsmasq-waze.log
